#!/bin/bash

echo "🚀 Marriage Bureau App Deployment Helper"
echo "========================================"
echo ""
echo "Your app is ready for deployment!"
echo ""
echo "📁 Deployment file created: MarriageBureauApp.zip"
echo ""
echo "🌐 Choose your deployment platform:"
echo ""
echo "1. Netlify (Recommended - Free & Easy)"
echo "   • Go to: https://netlify.com"
echo "   • Sign up for free"
echo "   • Drag & drop MarriageBureauApp.zip"
echo "   • Get your public URL"
echo ""
echo "2. Vercel (Alternative)"
echo "   • Go to: https://vercel.com"
echo "   • Sign up for free"
echo "   • Upload MarriageBureauApp.zip"
echo "   • Get your public URL"
echo ""
echo "3. GitHub Pages"
echo "   • Create GitHub repository"
echo "   • Upload all files"
echo "   • Enable GitHub Pages"
echo "   • Get your public URL"
echo ""
echo "✅ After deployment, your share links will work on all devices!"
echo ""
echo "📱 Share URLs will look like:"
echo "   • Form: https://your-app.netlify.app?form=share"
echo "   • Profile: https://your-app.netlify.app?profile=encoded_data"
echo ""
echo "🎉 Happy deploying!"
